version: "3.7"
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dev-container
    volumes:
      - /home:/home/work
      - /tmp/.X11-unix:/tmp/.X11-unix/
    environment:
      - DISPLAY
    command: tail -f /dev/null